export const soccerSkillTrees = [
    {
        name: "Dribbling",
        description: "Beat defenders with close control and creative skill moves",
        icon: "⚽",
        display_order: 0,
        nodes: [
            { name: "Close Control", description: "Keep the ball tight to your feet while moving at speed", level: 1, xp_required: 100, icon: "🦶", display_order: 0 },
            { name: "Body Feints", description: "Sell a fake direction with your body to unbalance defenders", level: 1, xp_required: 150, icon: "🎭", display_order: 1 },
            { name: "Step Over", description: "Drag your foot over the ball to shift the defender's weight", level: 2, xp_required: 250, icon: "🦵", display_order: 2 },
            { name: "Cruyff Turn", description: "Cut the ball behind your standing leg to quickly change direction", level: 2, xp_required: 300, icon: "↩️", display_order: 3 },
            { name: "Elastico", description: "Flick the ball one way then snap it back the opposite direction", level: 3, xp_required: 400, icon: "⚡", display_order: 4 },
            { name: "1v1 Mastery", description: "Combine moves fluidly in game situations to beat any defender", level: 3, xp_required: 500, icon: "🏆", display_order: 5 },
        ],
    },
    {
        name: "Passing",
        description: "Become the playmaker with precise passing at every range",
        icon: "📐",
        display_order: 1,
        nodes: [
            { name: "Short Pass", description: "Accurate inside-of-the-foot passes to nearby teammates", level: 1, xp_required: 100, icon: "➡️", display_order: 0 },
            { name: "First Touch", description: "Control the ball cleanly with your first touch to set up the next action", level: 1, xp_required: 150, icon: "🫳", display_order: 1 },
            { name: "Through Ball", description: "Weight a pass into space for a teammate's run behind the defense", level: 2, xp_required: 250, icon: "🎯", display_order: 2 },
            { name: "Long Ball", description: "Switch play or find runners with accurate long-range passes", level: 2, xp_required: 300, icon: "🏈", display_order: 3 },
            { name: "One-Touch Passing", description: "Play quick combinations without taking an extra touch", level: 3, xp_required: 400, icon: "⚡", display_order: 4 },
            { name: "Visionary Passing", description: "See and execute creative passes that unlock defenses", level: 3, xp_required: 500, icon: "👁️", display_order: 5 },
        ],
    },
    {
        name: "Shooting",
        description: "Finish chances with power and precision",
        icon: "🥅",
        display_order: 2,
        nodes: [
            { name: "Instep Drive", description: "Power shot using the laces with proper technique", level: 1, xp_required: 100, icon: "💥", display_order: 0 },
            { name: "Placement Shot", description: "Side-foot finish aimed at the corners of the goal", level: 1, xp_required: 150, icon: "🎯", display_order: 1 },
            { name: "One-on-One Finishing", description: "Stay calm and pick your spot when through on goal", level: 2, xp_required: 250, icon: "🧊", display_order: 2 },
            { name: "Volleys", description: "Strike the ball cleanly out of the air from crosses", level: 2, xp_required: 300, icon: "✈️", display_order: 3 },
            { name: "Free Kicks", description: "Curve or dip free kicks over the wall and into the goal", level: 3, xp_required: 400, icon: "🌀", display_order: 4 },
            { name: "Headers", description: "Direct headers on target from crosses and set pieces", level: 3, xp_required: 500, icon: "🗣️", display_order: 5 },
        ],
    },
    {
        name: "Defending",
        description: "Win the ball back and shut down attackers",
        icon: "🛡️",
        display_order: 3,
        nodes: [
            { name: "Jockeying", description: "Stay on your feet and force the attacker where you want them", level: 1, xp_required: 100, icon: "🧎", display_order: 0 },
            { name: "Standing Tackle", description: "Time your tackle to win the ball cleanly", level: 1, xp_required: 150, icon: "🦶", display_order: 1 },
            { name: "Interceptions", description: "Read passing lanes and step in to win the ball", level: 2, xp_required: 250, icon: "✋", display_order: 2 },
            { name: "Heading Clearances", description: "Win aerial duels and clear danger from crosses and corners", level: 2, xp_required: 300, icon: "⬆️", display_order: 3 },
            { name: "Recovery Runs", description: "Track back at speed to get between the attacker and goal", level: 3, xp_required: 400, icon: "🏃‍♂️", display_order: 4 },
            { name: "1v1 Defending", description: "Contain and dispossess attackers in isolation situations", level: 3, xp_required: 500, icon: "🔒", display_order: 5 },
        ],
    },
    {
        name: "Set Pieces",
        description: "Master dead-ball situations to create and score goals",
        icon: "📐",
        display_order: 4,
        nodes: [
            { name: "Corner Kicks", description: "Deliver accurate corners to dangerous areas", level: 1, xp_required: 100, icon: "🚩", display_order: 0 },
            { name: "Throw-Ins", description: "Long and accurate throw-ins to maintain possession", level: 1, xp_required: 100, icon: "🙌", display_order: 1 },
            { name: "Direct Free Kicks", description: "Score directly from free kick positions", level: 2, xp_required: 300, icon: "🎯", display_order: 2 },
            { name: "Indirect Free Kicks", description: "Execute rehearsed routines from indirect positions", level: 2, xp_required: 250, icon: "🔀", display_order: 3 },
            { name: "Penalty Kicks", description: "Consistent penalty technique with placement and composure", level: 3, xp_required: 400, icon: "🎪", display_order: 4 },
            { name: "Set Piece Routines", description: "Design and execute creative set piece plays with teammates", level: 3, xp_required: 500, icon: "📋", display_order: 5 },
        ],
    },
];
