export const volleyballSkillTrees = [
    {
        name: "Attacking",
        description: "Dominate at the net with powerful and smart hitting",
        icon: "💥",
        display_order: 0,
        nodes: [
            { name: "Approach Footwork", description: "Three-step or four-step approach with explosive last two steps", level: 1, xp_required: 100, icon: "👟", display_order: 0 },
            { name: "Arm Swing", description: "Full arm swing with proper elbow position and wrist snap", level: 1, xp_required: 150, icon: "💪", display_order: 1 },
            { name: "Cross-Court Hit", description: "Attack the ball at an angle across the court", level: 2, xp_required: 250, icon: "↗️", display_order: 2 },
            { name: "Line Shot", description: "Hit down the sideline past the block", level: 2, xp_required: 300, icon: "📏", display_order: 3 },
            { name: "Tips & Roll Shots", description: "Off-speed attacks that drop behind the block", level: 3, xp_required: 400, icon: "🪶", display_order: 4 },
            { name: "Tool the Block", description: "Use the blockers' hands to deflect the ball out of bounds", level: 3, xp_required: 500, icon: "🧠", display_order: 5 },
        ],
    },
    {
        name: "Serving",
        description: "Put opponents on their heels with tough serves",
        icon: "🎯",
        display_order: 1,
        nodes: [
            { name: "Underhand Serve", description: "Consistent underhand serve to get the ball in play", level: 1, xp_required: 100, icon: "🤚", display_order: 0 },
            { name: "Float Serve", description: "Overhand serve with no spin that moves unpredictably", level: 1, xp_required: 150, icon: "🌊", display_order: 1 },
            { name: "Topspin Serve", description: "Overhand serve with heavy topspin that drops fast", level: 2, xp_required: 250, icon: "🔄", display_order: 2 },
            { name: "Jump Serve", description: "Toss, approach, and attack the serve with power from a jump", level: 2, xp_required: 300, icon: "⬆️", display_order: 3 },
            { name: "Zone Targeting", description: "Serve to specific zones to exploit weak passers", level: 3, xp_required: 400, icon: "🎯", display_order: 4 },
            { name: "Ace Machine", description: "Combine power and placement to earn direct points on serve", level: 3, xp_required: 500, icon: "🔥", display_order: 5 },
        ],
    },
    {
        name: "Passing & Defense",
        description: "Build a rock-solid platform and dig everything",
        icon: "🛡️",
        display_order: 2,
        nodes: [
            { name: "Platform Passing", description: "Form a flat platform with arms together for consistent bumps", level: 1, xp_required: 100, icon: "🤲", display_order: 0 },
            { name: "Serve Receive", description: "Read the server and pass to target for a clean first ball", level: 1, xp_required: 150, icon: "📥", display_order: 1 },
            { name: "Defensive Base", description: "Low ready position with weight forward, ready to react", level: 2, xp_required: 250, icon: "🧎", display_order: 2 },
            { name: "Digging", description: "Get low and absorb hard-driven attacks to keep the ball alive", level: 2, xp_required: 300, icon: "⬇️", display_order: 3 },
            { name: "Pancake", description: "Slide your hand flat under the ball at the last second to save it", level: 3, xp_required: 400, icon: "🥞", display_order: 4 },
            { name: "Pursuit Digs", description: "Chase down balls off the court and keep rallies alive", level: 3, xp_required: 500, icon: "🏃", display_order: 5 },
        ],
    },
    {
        name: "Setting",
        description: "Run the offense with precise and deceptive sets",
        icon: "🙌",
        display_order: 3,
        nodes: [
            { name: "Hand Position", description: "Shape your hands above your forehead with proper finger spacing", level: 1, xp_required: 100, icon: "🤚", display_order: 0 },
            { name: "Outside Sets", description: "Consistent high sets to the outside hitters", level: 1, xp_required: 150, icon: "➡️", display_order: 1 },
            { name: "Back Sets", description: "Set behind you to the right side with accuracy and disguise", level: 2, xp_required: 250, icon: "↩️", display_order: 2 },
            { name: "Quick Sets", description: "Fast tempo sets to the middle for quick attacks", level: 2, xp_required: 300, icon: "⚡", display_order: 3 },
            { name: "Jump Setting", description: "Set while jumping to speed up the offense and add deception", level: 3, xp_required: 400, icon: "⬆️", display_order: 4 },
            { name: "Dump & Setter Attack", description: "Surprise the defense by attacking on the second contact", level: 3, xp_required: 500, icon: "🎭", display_order: 5 },
        ],
    },
    {
        name: "Blocking",
        description: "Shut down attackers at the net with timing and technique",
        icon: "✋",
        display_order: 4,
        nodes: [
            { name: "Ready Position", description: "Hands high, feet shoulder-width apart, eyes on the setter", level: 1, xp_required: 100, icon: "🧎", display_order: 0 },
            { name: "Footwork", description: "Shuffle or crossover step to get in front of the hitter", level: 1, xp_required: 150, icon: "👟", display_order: 1 },
            { name: "Penetration", description: "Press hands over the net to take away hitting angles", level: 2, xp_required: 250, icon: "🫱", display_order: 2 },
            { name: "Closing the Block", description: "Move together with teammates to seal the gap", level: 2, xp_required: 300, icon: "🤝", display_order: 3 },
            { name: "Reading the Hitter", description: "Watch the hitter's approach and arm to anticipate the shot", level: 3, xp_required: 400, icon: "👀", display_order: 4 },
            { name: "Solo Blocks", description: "Time and position a one-person block to stuff the attacker", level: 3, xp_required: 500, icon: "🚫", display_order: 5 },
        ],
    },
];
